services:
  memcached:
    image: memcached:alpine
    ports:
      - "11211:11211"

  backend:
    build: .
    ports:
      - "8080:8080"
    environment:
      - MEMCACHED_HOST=memcached
      - MEMCACHED_PORT=11211
    depends_on:
      - memcached

  frontend:
    build: ../poc-frontend
    ports:
      - "4200:80"
    depends_on:
      - backend

  proxy:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
